#!/usr/bin/env bash
# Installs Sentinel Agent as a macOS LaunchAgent: starts at login, auto-
# restarts if it crashes. Run `npm run build:dashboard` at least once
# before installing (the dashboard's compiled JS is not generated by
# this script).
set -euo pipefail

AGENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NODE_PATH="$(command -v node)"
PLIST_LABEL="com.sentinel.agent"
PLIST_DEST="$HOME/Library/LaunchAgents/${PLIST_LABEL}.plist"

if [ -z "$NODE_PATH" ]; then
  echo "Could not find 'node' on PATH. Install Node.js first." >&2
  exit 1
fi

mkdir -p "$AGENT_DIR/logs"

sed -e "s|__NODE_PATH__|${NODE_PATH}|g" -e "s|__AGENT_DIR__|${AGENT_DIR}|g" \
  "$AGENT_DIR/launchd/com.sentinel.agent.plist.template" > "$PLIST_DEST"

echo "Wrote $PLIST_DEST"

# Unload first in case it's already running from a previous install.
launchctl bootout "gui/$(id -u)" "$PLIST_DEST" 2>/dev/null || true

launchctl bootstrap "gui/$(id -u)" "$PLIST_DEST"
launchctl enable "gui/$(id -u)/${PLIST_LABEL}"

echo "Sentinel Agent installed and running as a LaunchAgent."
echo "Dashboard: http://localhost:4100"
echo "Logs: $AGENT_DIR/logs/agent.log"
echo "To uninstall: ./scripts/uninstall.sh"
